#!/bin/sh

set -eu

# shellcheck disable=SC1007
TEST_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
# shellcheck source=./.environment.sh
. "${TEST_DIR}/.environment.sh"

#shellcheck source=lib/assert-crowdsec-not-running.sh
. "${TEST_DIR}/lib/assert-crowdsec-not-running.sh"

CSCLI="${BIN_DIR}/cscli"
CROWDSEC="${BIN_DIR}/crowdsec"

"${TEST_DIR}/instance-data" load

hubdir="${LOCAL_DIR}/hub-tests"
git clone --depth 1 https://github.com/crowdsecurity/hub.git "${hubdir}" || (cd "${hubdir}"; git pull)

HUBTESTS_BATS="${TEST_DIR}/dyn-bats/99_hub.bats"

cat <<EOT > "${HUBTESTS_BATS}"
set -u

FILE="\$(basename "\${BATS_TEST_FILENAME}" .bats):"
load "\${TEST_DIR}/lib/bats-support/load.bash"
load "\${TEST_DIR}/lib/bats-assert/load.bash"

CSCLI="\${BIN_DIR}/cscli"
CROWDSEC="\${BIN_DIR}/crowdsec"

setup_file() {
    . "\${TEST_DIR}/lib/assert-crowdsec-not-running.sh"
}
EOT

for testname in $("${CSCLI}" --crowdsec "${CROWDSEC}" --cscli "${CSCLI}" hubtest --hub "${hubdir}" list -o json | grep -v NAME | grep -v -- '-------' | awk '{print $1}'); do
    cat << EOT >> "${HUBTESTS_BATS}"

@test "\$FILE $testname" {
    run "\${CSCLI}" --crowdsec "\${CROWDSEC}" --cscli "\${CSCLI}" --hub "${hubdir}" hubtest run "${testname}" --clean
    # in case of error, need to see what went wrong
    echo "\$output"
    assert_success
}
EOT
done
